#Set.union() Operation

##Cara 1

In [ ]:
n = int(input())
set1 = set(map(int,input().split()))
b = int(input())
set2 = set(map(int,input().split()))
u = set1.union(set2)
print(len(u))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


##Cara 2

In [ ]:
n, n_set, b, b_set = int(input()), set(map(int, input().split())), int(input()), set(map(int, input().split()))
f = n_set.union(b_set)
print(len(f))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


##Cara 3

In [ ]:
var1 = int(input()) 
set1 = set(map(int, input().split())) 
var2 = int(input()) 
set2 = set(map(int,input().split())) 
print(len(set1.union(set2)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


#Set .intersection() Operation


##Cara 1

In [ ]:
n = int(input()) 
set1= set(input().split())

b = int(input()) 
set2= set(input().split())

u = set1.intersection(set2) 
print(len(u))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


##Cara 2

In [ ]:
contents1 = int(input())
nums1 = input()
nums1 = list(map(int, nums1.split()))
contents2 = int(input())
nums2 = input()
nums2 = list(map(int, nums2.split()))
overlaps = 0
for nums in nums1:
    for digits in nums2:
        if digits == nums:
            overlaps = overlaps + 1
print(overlaps)

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


##Cara 3

In [ ]:
n, English, b, French = int(input()), set(map(int, input().split())), int(input()), set(map(int, input().split()))
print(len(English.intersection(French)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


#Set.difference() Operation

##Cara 1

In [ ]:
n_English = input()
r_English = set(map(int, input().split()))
n_French = input()
r_French = set(map(int, input().split()))
print(len(r_English.difference(r_English.intersection(r_French))))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


##Cara 2

In [ ]:
n, English, b, French = int(input()), set(map(int, input().split())), int(input()), set(map(int, input().split()))
print(len(English.difference(French)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


##Cara 3

In [ ]:
var1 = int(input()) 
set1 = set(map(int, input().split())) 
var2 = int(input()) 
set2 = set(map(int,input().split())) 
print(len(set1-set2))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


##Cara 4

In [ ]:
n = int(input()) 
E_N_S = input().split() 
s = set() 
for item in E_N_S: s.add(int(item))

b = int(input()) 
F_N_S = input().split() 
fs = set() 
for item in F_N_S: fs.add(int(item))

deference = s.difference(fs) 
deference_list = [] 
for deferences in deference: deference_list.append(deferences)

length_of_deference = len(deference_list) 
print(length_of_deference)

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


##Cara 5

In [ ]:
n=int(input())
english=set(map(int,input().split()))

b=int(input())
french=set(map(int,input().split()))

    
common_students=english.difference(french)

print(len(common_students))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


#Set.symmetric.difference() Operation

##Cara 1

In [ ]:
E=int(input())
E_r=set(map(int,input().split()))
f=int(input())
f_r=set(map(int,input().split()))

sym_diff=E_r.symmetric_difference(f_r)

tos=len(sym_diff)

print(tos)

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


##Cara 2

In [ ]:
n, English, b, French = int(input()), set(map(int, input().split())), int(input()), set(map(int, input().split()))
print(len(English.symmetric_difference(French)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


##Cara 3

In [ ]:
var1 = int(input()) 
set1 = set(map(int, input().split())) 
var2 = int(input()) 
set2 = set(map(int,input().split())) 
print(len(set1.symmetric_difference(set2)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


#Set Mutations

##Cara 1

In [ ]:
n = int(input()) 
A_set_l = input().split() 
A_set = set()

for i in A_set_l: 
  A_set.add(int(i))

for _ in range(int(input())): 
  operation, length = input().split() 
  other_set = set(map(int, input().split()))

if operation == "intersection_update":
    A_set.intersection_update(other_set)
if operation == "update":
    A_set.update(other_set)
if operation == "symmetric_difference_update":
    A_set.symmetric_difference_update(other_set)
if operation == "difference_update":
    A_set.difference_update(other_set)

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66


##Cara 2

In [ ]:
n = int(input())

lst = set(map(int,input().split()))

t = int(input())

for _ in range(t):
    a,b = input().split()
    b_lst = map(int,input().split())
    getattr(lst,a)(b_lst)
    
print(sum(lst))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


##Cara 3

In [ ]:
A=int(input())
set_A=set(map(int,input().split()))
n=int(input())

for i in range(n):
    op=input().split()
    o=set(map(int,input().split()))
    if op[0]=='update':
        set_A.update(o)
    elif op[0]=='intersection_update':
        set_A.intersection_update(o)
    elif op[0]=='difference_update':
        set_A.difference_update(o)
    elif op[0]=='symmetric_difference_update':
        set_A.symmetric_difference_update(o)

print(sum(set_A))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


#Iterables and Iterators

##Cara 1

In [ ]:
from itertools import combinations
n,word, k = int(input()), input().split(), int(input())
word_per = list(combinations(word,k))
count=0
for i in word_per:
    if ('a' in i):
        count+=1
print(count/len(word_per))

4
a a c d
2
0.8333333333333334


##Cara 2

In [ ]:
import math
a=input()
b=input()
c=input()
our_str=''.join(b.split())
c=int(c)
a=our_str.count('a')
l=len(our_str)
if c > l-a:
    answer=1
else:
    answer=1-math.factorial(l-a)/math.factorial(l-a-c)/math.factorial(l)*math.factorial(l-c)
    
print(answer)

4
a a c d
2
0.8333333333333334


##Cara 3

In [ ]:
import itertools

num = int(input()) 
new = input().replace(" ", "") 
group = int(input())

combinations = list(itertools.combinations(new, group))

repeatation = 0 
for i in combinations: 
  if "a" in i: repeatation = repeatation + 1

result = float(repeatation/ len(combinations)) 
print("{:.3}".format(result))

4
a a c d
2
0.833


##Cara 4

In [ ]:
from math import comb
n = input()
l = input().split()
k = int(input())

print("{:.3f}".format(1- comb(len(l)-l.count('a'),2)/comb(len(l),2)))

4
a a c d
2
0.833


##Cara 5

In [ ]:
# we are an int N, a split() string and another int K
from itertools import permutations, combinations

N, arr, K, num_arr = int(input()), input().split(), int(input()), []
for i in range(len(arr)):
    if arr[i] == 'a':
        num_arr.append(i + 1)

count = 0
for i in combinations(range(1, N + 1), K):
    if len(set(i).intersection(set(num_arr))) > 0:
        count += 1

list1 = list(combinations(range(1, N+1), K))
print(round(count/len(list1), 3))

4
a a c d
2
0.833


#Mximize It!

##Cara 1

In [ ]:
import itertools

#The first line contains 2 space separated integers K and M. 
#The next K lines each contains an N-integer denoting the number of elements in list and follow by the N number input

K, M = map(int, input().split())

lst = []
K_lst = []
for i in range(K):
  lst = list(map(int, input().split()))
  #extract N-integer list in 'lst' 
  K_lst.append(lst[1:1+lst[0]])

#Get all possible combinations from number from each sublist
combination = list(itertools.product(*K_lst))
combination = list(set(combination))

#Take exactly one element from each list, not necessarily the largest element. 
#You add the squares of the chosen elements and perform the modulo operation. 
#The maximum value that you can obtain, will be the answer to the problem

result = []
for subtuple in combination:
  fx = list(map(lambda x: x**2, subtuple))
  modulus = sum(fx)%M
  result.append(modulus)
print(max(result))

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


##Cara 2

In [ ]:
from itertools import product
K, M = list(map(int, input().split()))
lst, opt = [], []

for i in range(K):
    lst.append(list(map(int, input().split()[1:])))
for i in product(*lst):
    opt.append(sum([x**2 for x in i]) % M)
    
print(max(opt))

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


##Cara 3

In [ ]:
import itertools

k, m = list(map(int, input().split()))
squares = []
for _ in range(k):
    _, *square = [i**2 for i in list(map(int, input().split()))]
    squares.append(square)

max_f = 0
for p in itertools.product(*squares):
    max_f = max(max_f, sum(p) % m)
print(max_f)

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


##Cara 4

In [ ]:
import itertools
req_list=[]
k,m=input().split()
m=int(m)
k=int(k)
lists=[]
for i in range(k):
    lists+=[[int(a)**2 for a in input().split()[1:]]]
for item in itertools.product(*lists):
    req_list.append(sum(item)%m)
print(max(req_list))

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


##Cara 5

In [ ]:
from itertools import groupby, product


K, M = list(map(int, input().split()))

def f(x):
    return (int(x)**2)%M #since (a+b)mod(c) = a mod(c) + b mod(c)
		
Nels, vals= [], []
for i in range(K):
    ipt = input().split()
    newval = [k for k, g in groupby(map(f, ipt[1:]))] #The groupby is to get rid of redundant values 
    Nels.append(len(newval))
    vals.append(newval)
prd = product(*vals)
resum = [sum(list(sub))%M for sub in prd]
print(max(resum))

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


#Linear Algebra

##Cara 1

In [ ]:
import numpy
n=int(input())
array_A=[]
for i in range(1,n+1):
    element=list(map(float,input().split()))
    array_A.append(element)
    
print(round(numpy.linalg.det(array_A),2))

2
1.1 1.1
1.1 1.1
0.0


##Cara 2

In [ ]:
from numpy.linalg import det

print(round(det([[float(x) for x in input().split()] for _ in range(int(input()))]), 2))

2
1.1 1.1
1.1 1.1
0.0


##Cara 3

In [ ]:
import numpy

N = int(input())

A = numpy.array([input().split() for _ in range(N)], float)

print(round(numpy.linalg.det(A), 2))

2
1.1 1.1
1.1 1.1
0.0


##Cara 4

In [ ]:
import numpy

arr = []
for _ in range(int(input())):
    arr.append(list(map(float,input().split())))
out = numpy.linalg.det(numpy.array(arr))
#print("{0:.2f}".format(out))
print(round(out,2))

2
1.1 1.1
1.1 1.1
0.0


#Arrays

##Cara 1

In [ ]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return numpy.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


##Cara 2

In [ ]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    my_array = []
    a = numpy.array(arr, float)
    for i in range(len(a)):
        my_array.append(a[(len(a)-1)-i])
        
    return numpy.array(my_array,float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


#Shape and Reshape

##Cara 1

In [ ]:
import numpy 
arr = list(map(int, input().split())) 
my_array = numpy.array(arr) 
print(numpy.reshape(my_array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Cara 2

In [ ]:
import numpy as np
inp_arr = np.array([int(i) for i in input().strip().split(' ')], dtype = int).reshape(3, 3)
print(inp_arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Cara 3

In [ ]:
import numpy

ar1=input().strip().split(' ') 
ar=numpy.array(ar1,int) 
ar2=numpy.reshape(ar,(3,3)) 
print(ar2)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Cara 4

In [ ]:
l = list(map(int,input().split()))
l1 = "[{0} {1} {2}]".format(l[0], l[1], l[2])
l2 = "[{0} {1} {2}]".format(l[3], l[4], l[5])
l3 = "[{0} {1} {2}]".format(l[6], l[7], l[8])

print("[{0}\n {1}\n {2}]".format(l1, l2, l3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#The Captain's Room

##Cara 1

In [ ]:
from collections import Counter

_ = input()
rooms = Counter(input().split())

print(sorted(rooms.items(), key=lambda x: x[1])[0][0])

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


##Cara 2

In [ ]:
from collections import Counter

K = input()
rooms = Counter(input().split())
print(rooms.most_common()[-1][0])

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 
8


##Cara 3

In [ ]:
from collections import Counter

groups = input()
rooms: list = input().split()

rooms_count = Counter(rooms)
sorted_rooms = sorted(rooms_count.items(), key=lambda x: x[1])
print(sorted_rooms[0][0])

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


##Cara 4

In [ ]:
from collections import Counter

k=int(input())
lst=input().split()

captains_key=[]

counts=Counter(lst)

for element,count in counts.items():
    if count==1:
        captains_key.append(element)
        
print(*captains_key)

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


##Cara 5

In [ ]:
K = int(input())
RmNumLst = [int(i) for i in input().split()]
RmSet = set(RmNumLst)

sum_lst = sum(RmNumLst)
sum_set = sum(RmSet)

CptRmNum = int(sum_set - ((sum_lst - sum_set) / (K - 1)))

print(CptRmNum)

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


#Check Subset

##Cara 1

In [ ]:
n = int(input())
for i in range(n):
  k, A = input(), set(map(int, input().split()))
  j, B = input(), set(map(int, input().split()))
  print(A.issubset(B))

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


##Cara 2

In [ ]:
n=int(input())

for i in range(n):
    k,A=input(),set(map(int,input().split()))    
    j,B=input(),set(map(int,input().split()))
    if A.issubset(B): print(True)
    else:print(False)

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


##Cara 3

In [ ]:
T=int(input())

for _ in range(T):
    cardA=int(input())
    A=set(input().split())
    cardB=int(input())
    B=set(input().split())
    
    union=A.union(B)
    if(union==B):
        print(True)
    else:
        print(False)

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


##Cara 4

In [ ]:
n_tests=int(input())
for i in range(n_tests):
    string1_len=input()
    string1=input().split(" ")
    srings2_len=input()
    string2=input().split(" ")

    is_subset= [x in string2 for x in string1]
    if False in is_subset:
        print(False)
    else:
        print(True)

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


#Check Strict Superset

##Cara 1

In [ ]:
set_A = set(map(int, input().split()))
flag = all(set(map(int, input().split())).issubset(set_A) for _ in range(int(input())))
print(flag)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


## Cara 2

In [ ]:
A=set(map(int,input().split()))
n=int(input())
other_set=[]

flag=0
for i in range(n):
    s=set(map(int,input().split()))
    other_set.append(s)
    if A.issuperset(other_set[i]):
        if len(A.difference(other_set[i]))>=1:
            flag+=1
        else:
            print("False")
    else:
        print("False")
        break
if flag==n:
    print("True")

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


##Cara 3

In [ ]:
set_A=set(map(int,input().split()))
n=int(input())
other=set()
for i in range(n):
    element=map(int,input().split())
    other.update(element)
    
print(set_A.issuperset(other))

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


##Cara 4

In [ ]:
set_A = set(map(int, input().split()))

flag = True
for _ in range(int(input())):
    set_n = set(map(int, input().split()))
    if not set_A.issuperset(set_n):
        flag = False
print(flag)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


##Cara 5

In [ ]:
set_A = set(map(int, input().split()))
flag = True
for _ in range(int(input())):
    set_n = set(map(int, input().split()))
    if not set_A.issuperset(set_n):
        flag = False
print(flag)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


#Zeros and Ones

##Cara 1

In [ ]:
import numpy as np
dim = tuple(map(int, input().strip().split(' ')))
print(np.zeros(dim, dtype = np.int32), np.ones(dim, dtype = np.int32), sep = '\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


##Cara 2

In [ ]:
import numpy

shape = list(map(int, input().split()))
print(numpy.zeros(shape, int))
print(numpy.ones(shape, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


##Cara 3

In [ ]:
import numpy

arr = [int(x) for x in input().split()]
print(numpy.zeros(arr, dtype=int), numpy.ones(arr, dtype=int), sep="\n")

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


#Eye and Identify

##Cara 1

In [ ]:
import numpy as np
np.set_printoptions(legacy = '1.13')
n, m = list(map(int, input().strip().split(' ')))
print(np.eye(n, m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


##Cara 2

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')
print(np.eye(*(map(int,input().split()))))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


##Cara 3

In [ ]:
import numpy

numpy.set_printoptions(legacy='1.13')

read=list(map(int,input().split()))

print(numpy.eye(read[0],read[1]))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


##Cara 4

In [ ]:
import numpy 
numpy.set_printoptions(legacy='1.13') 
N,M = map (int, input().split()) 
arr= numpy.eye(N,M) 
print(arr)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


##Cara 5

In [ ]:
import numpy 
numpy.set_printoptions(legacy='1.13')

N,M=(input().split()) 
N=int(N) 
M=int(M) 
print(numpy.eye(N,M,k=0)) 

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#Classes: Dealing with Complex Number

##Cara 1

In [ ]:
import math
class Complex(object):
    def __init__(self, real, imaginary):
        self.complex = complex(real, imaginary)
        self.real = self.complex.real
        self.imaginary = self.complex.imag

    def __add__(self, no):
        res = self.complex + complex(no.real, no.imaginary)

        return Complex(res.real, res.imag)

    def __sub__(self, no):
        res = self.complex - complex(no.real, no.imaginary)

        return Complex(res.real, res.imag)

    def __mul__(self, no):
        res = self.complex * complex(no.real, no.imaginary)

        return Complex(res.real, res.imag)

    def __truediv__(self, no):
        res = self.complex / complex(no.real, no.imaginary)

        return Complex(res.real, res.imag)

    def mod(self):
        res = abs(self.complex)

        return Complex(res.real, res.imag)
    
    def __str__(self):
        if self.imaginary == 0:
            result = "%.2f+0.00i" % (self.real)
        elif self.real == 0:
            if self.imaginary >= 0:
                result = "0.00+%.2fi" % (self.imaginary)
            else:
                result = "0.00-%.2fi" % (abs(self.imaginary))
        elif self.imaginary > 0:
            result = "%.2f+%.2fi" % (self.real, self.imaginary)
        else:
            result = "%.2f-%.2fi" % (self.real, abs(self.imaginary))
        return result

if __name__ == '__main__':
    c = map(float, input().split())
    d = map(float, input().split())
    x = Complex(*c)
    y = Complex(*d)
    print(*map(str, [x+y, x-y, x*y, x/y, x.mod(), y.mod()]), sep='\n')

2 1
5 6
7.00+7.00i
-3.00-5.00i
4.00+17.00i
0.26-0.11i
2.24+0.00i
7.81+0.00i


##Cara 2

In [ ]:
import math
class Complex(object):
    def __init__(self, real, imaginary):
        self.real = real
        self.imaginary = imaginary
    def __add__(self, no):
        real = self.real + no.real
        imaginary = self.imaginary + no.imaginary
        return Complex(real, imaginary)
    def __sub__(self, no):
        real = self.real - no.real
        imaginary = self.imaginary - no.imaginary
        return Complex(real, imaginary)
    def __mul__(self, no):
        real = self.real * no.real - self.imaginary * no.imaginary
        imaginary = self.real * no.imaginary + self.imaginary * no.real
        return Complex(real, imaginary)
    def __truediv__(self, no):
        x = float(no.real ** 2 + no.imaginary ** 2)
        y = self * Complex(no.real, -no.imaginary)
        real = y.real / x
        imaginary = y.imaginary / x
        return Complex(real, imaginary)

    def mod(self):
        real = math.sqrt(self.real ** 2 + self.imaginary ** 2)
        return Complex(real, 0)

    def __str__(self):
        if self.imaginary == 0:
            result = "%.2f+0.00i" % (self.real)
        elif self.real == 0:
            if self.imaginary >= 0:
                result = "0.00+%.2fi" % (self.imaginary)
            else:
                result = "0.00-%.2fi" % (abs(self.imaginary))
        elif self.imaginary > 0:
            result = "%.2f+%.2fi" % (self.real, self.imaginary)
        else:
            result = "%.2f-%.2fi" % (self.real, abs(self.imaginary))
        return result
if __name__ == '__main__':
    c = map(float, input().split())
    d = map(float, input().split())
    x = Complex(*c)
    y = Complex(*d)
    print(*map(str, [x+y, x-y, x*y, x/y, x.mod(), y.mod()]), sep='\n')

2 1
5 6
7.00+7.00i
-3.00-5.00i
4.00+17.00i
0.26-0.11i
2.24+0.00i
7.81+0.00i


##Cara 3

In [ ]:
import math
def __add__(self, no):
    result = Complex(self.real + no.real , self.imaginary + no.imaginary)
    return result

def __sub__(self, no):
    result = Complex(self.real-no.real, self.imaginary-no.imaginary)
    return result

def __mul__(self, no):
    result = complex(self.real, self.imaginary)* complex(no.real,no.imaginary)
    return Complex(result.real, result.imag)

def __truediv__(self, no):
    result = complex(self.real,self.imaginary)/ complex(no.real, no.imaginary)
    return Complex(result.real, result.imag)

def mod(self):
    result = Complex((self.real**2 + self.imaginary**2)**0.5, 0)
    return result


def __str__(self):
    if self.imaginary == 0:
        result = "%.2f+0.00i" % (self.real)
    elif self.real == 0:
        if self.imaginary >= 0:
            result = "0.00+%.2fi" % (self.imaginary)
        else:
            result = "0.00-%.2fi" % (abs(self.imaginary))
    elif self.imaginary > 0:
        result = "%.2f+%.2fi" % (self.real, self.imaginary)
    else:
        result = "%.2f-%.2fi" % (self.real, abs(self.imaginary))
    return result
if __name__ == '__main__':
    c = map(float, input().split())
    d = map(float, input().split())
    x = Complex(*c)
    y = Complex(*d)
    print(*map(str, [x+y, x-y, x*y, x/y, x.mod(), y.mod()]), sep='\n')

2 1
5 6
7.00+7.00i
-3.00-5.00i
4.00+17.00i
0.26-0.11i
2.24+0.00i
7.81+0.00i


##Cara 4

In [ ]:
import math

class Complex(object):
    def __init__(self, real, imaginary):
        self.real = real
        self.imaginary = imaginary
        
    def __add__(self, no):
        return Complex(self.real + no.real, self.imaginary + no.imaginary)
        
    def __sub__(self, no):
        return Complex(self.real - no.real, self.imaginary - no.imaginary)
        
    def __mul__(self, no):
        return Complex(self.real * no.real - self.imaginary * no.imaginary, \
        self.imaginary * no.real + self.real * no.imaginary)
        
    def __truediv__(self, no):
        return Complex((self.real*no.real + self.imaginary*no.imaginary)/(no.real**2 + no.imaginary**2),\
        (self.imaginary*no.real - self.real*no.imaginary)/(no.real**2 + no.imaginary**2))
        
    def mod(self):
        return Complex((self.real**2 + self.imaginary**2)**0.5, 0)
        
    def __str__(self):
        if self.imaginary == 0:
            result = "%.2f+0.00i" % (self.real)
        elif self.real == 0:
            if self.imaginary >= 0:
                result = "0.00+%.2fi" % (self.imaginary)
            else:
                result = "0.00-%.2fi" % (abs(self.imaginary))
        elif self.imaginary > 0:
            result = "%.2f+%.2fi" % (self.real, self.imaginary)
        else:
            result = "%.2f-%.2fi" % (self.real, abs(self.imaginary))
        return result

if __name__ == '__main__':
    c = map(float, input().split())
    d = map(float, input().split())
    x = Complex(*c)
    y = Complex(*d)
    print(*map(str, [x+y, x-y, x*y, x/y, x.mod(), y.mod()]), sep='\n')

2 1
5 6
7.00+7.00i
-3.00-5.00i
4.00+17.00i
0.26-0.11i
2.24+0.00i
7.81+0.00i


#Find the Torsional Angle

In [ ]:
import math

class Points(object):
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
    def __sub__(self, no):
        return Points(self.x - no.x, self.y - no.y,self.z - no.z)
    def dot(self, no):
        return self.x*no.x + self.y*no.y + self.z*no.z
    def cross(self, no):
        return Points((self.y*no.z - self.z*no.y),(self.z*no.x - self.x*no.z),(self.x*no.y - self.y*no.x))
    def absolute(self):
        return pow((self.x ** 2 + self.y ** 2 + self.z ** 2), 0.5)

if __name__ == '__main__':
    points = list()
    for i in range(4):
        a = list(map(float, input().split()))
        points.append(a)

    a, b, c, d = Points(*points[0]), Points(*points[1]), Points(*points[2]), Points(*points[3])
    x = (b - a).cross(c - b)
    y = (c - b).cross(d - c)
    angle = math.acos(x.dot(y) / (x.absolute() * y.absolute()))

    print("%.2f" % math.degrees(angle))

0 4 5
1 7 6
0 5 9
1 7 2
8.19


#Hex Color Code

##Cara 1

In [ ]:
# we are supposed to print out valid hex color codes
# which has either 3 or 6 characters, that fall under[A-Fa-f0-9]
# they also have to begin with #
# we first find all the items between { and }, then find the hex codes
# we are given int N, and N lines of css code
import re
css_code = """"""
for i in range(int(input())):
    css_code += input() # the css code in one variable

neccessary_css_code = re.findall(r"[{][^}]+", css_code)
for item in neccessary_css_code:
    for i in re.findall(r"#[A-Fa-f0-9]{6}|#[A-Fa-f0-9]{3}", item):
        print(i)
    # print(*re.findall(r"#[A-Fa-f0-9]{6}|#[A-Fa-f0-9]{3}", item), sep="\n")
    

11
#BED
{
color: #FfFdF8; background-color:#aef;
font-size: 123px;
background: -webkit-linear-gradient(top, #f9f9f9, #fff); }
#Cab
{
background-color: #ABC;
border: 2px dashed #fff;
}

#FfFdF8
#aef
#f9f9f9
#fff
#ABC
#fff


##Cara 2

In [ ]:
import re
p=r'(?<=[:\s])(#{1}[0-9a-fA-F]{3,6}(?=[;\s,)]))'
for i in range(int(input())):
    html=input()
    m=re.findall(p,html)
    if len(m)>0:
        [print (i) for i in m]

11
#BED
{
color: #FfFdF8; background-color:#aef;
#FfFdF8
#aef
font-size: 123px;
background: -webkit-linear-gradient(top, #f9f9f9, #fff); }
#f9f9f9
#fff
#Cab
{
background-color: #ABC;
#ABC
border: 2px dashed #fff;
#fff
}



##Cara 3

In [ ]:
import re
no_input = int(input())
pattern = r'\#[a-fA-F0-9]{3,6}[;,)]'
for _ in range(no_input):
    user_input = input()
    matches = re.findall(pattern, user_input)
    for match in matches:
        if match[-1] == ',' or match[-1] == ')' or match[-1] == ';':
            match = match.replace(match[-1], '')
        print(match)

11
#BED
{
color: #FfFdF8; background-color:#aef;
#FfFdF8
#aef
font-size: 123px;
background: -webkit-linear-gradient(top, #f9f9f9, #fff); }
#f9f9f9
#fff
#Cab
{
background-color: #ABC;
#ABC
border: 2px dashed #fff
}



##Cara 4

In [ ]:
import re
p=re.compile(r'[ \:]+(\#[\da-fA-F]{3,6})')
for _ in range(int(input())):
    [print(i) for i in p.findall(input())]

11
#BED
{
color: #FfFdF8; background-color:#aef;
#FfFdF8
#aef
font-size: 123px;
background: -webkit-linear-gradient(top, #f9f9f9, #fff); }
#f9f9f9
#fff
#Cab
{
background-color: #ABC;
#ABC
border: 2px dashed #fff
#fff
}



#HTML Parser Part 1

##Cara 1

In [ ]:
from html.parser import HTMLParser
import re

class MyHtmlParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(f'Start : {tag}')
        [print(f'-> {i[0]} > {i[1]}') for i in attrs]
    def handle_endtag(self, tag):
        print(f'End   : {tag}')
    def handle_startendtag(self, tag, attrs):
        print(f'Empty : {tag}')
        [print(f'-> {i[0]} > {i[1]}') for i in attrs]

sec=re.compile(r'\<\!\-\-(.*)\-\-\>')
sc=re.compile(r'^(.*)(\<\!\-\-.*)$')
se=re.compile(r'^(.*\-\-\>)(.*)$')
isCommentStart=False
for _ in range(int(input())):
    s=input()
    s=sec.sub('',s)
    
    if(not isCommentStart and sc.match(s)):
        isCommentStart=True
        s=sc.sub(r'\1',s)
    
    if(isCommentStart and se.match(s)):
        isCommentStart=False
        s=se.sub(r'\2',s)
    elif(isCommentStart):
        continue
    
    parser = MyHtmlParser()
    parser.feed(s)

2
<html><head><title>HTML Parser - I</title></head>
Start : html
Start : head
Start : title
End   : title
End   : head
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


##Cara 2

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from html.parser import HTMLParser

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        for i in attrs:
            print(f"-> {i[0]} > {i[1]}")
    def handle_endtag(self, tag):
        print("End   :", tag)
    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        for i in attrs:
            print(f"-> {i[0]} > {i[1]}")

# instantiate the parser and fed it some HTML
parser = MyHTMLParser()
for _ in range(int(input())):
    parser.feed(input())

2
<html><head><title>HTML Parser - I</title></head>
Start : html
Start : head
Start : title
End   : title
End   : head
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


#HTML Parser Part 1

##Cara 1

In [ ]:
from html.parser import HTMLParser
import re

class MyHTMLParser(HTMLParser):
  
      def handle_comment(self, data):
        if re.search(r'\n', data):
            print('>>> Multi-line Comment')
            print(data)
        else:
            print('>>> Single-line Comment')
            print(data)

      def handle_data(self, data):
        if data!='\n':
            print(">>> Data")
            print(data)
  
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


##Cara 2

In [ ]:
from html.parser import HTMLParser
import re

class myparser(HTMLParser):
    def handle_comment(self, data1):
        if '\n' in data1:
            print('>>> Multi-line Comment',data1,sep='\n')
        else:
            print('>>> Single-line Comment',data1,sep='\n')
    def handle_data(self, data2):
        if data2:
            if re.findall(r'\n+',data2):
                data2=re.sub(r'\n+','',data2)
            else:
                print('>>> Data',data2,sep='\n')
                
html = ""       

for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = myparser()
parser.feed(html)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


##Cara 3

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if '\n' in data:
            print (">>> Multi-line Comment", data,sep='\n')
        else:
            print (">>> Single-line Comment", data,sep='\n')
    def handle_data(self, data):
        if data != '\n':
            print (">>> Data", data,sep='\n')

  
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]
>>> Data

>>> Multi-line Comment



#Zipped

##Cara 1

In [ ]:
_, X = input().split()
for s in zip(*[map(float, input().split()) for _ in range(int(X))]):
    print(f"{sum(s)/len(s):.1f}")

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


##Cara 2

In [ ]:
_, X = input().split()
for s in zip(*[list(map(float, input().split())) for _ in range(int(X))]):
    print(f"{sum(s)/len(s):.1f}")

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


##Cara 3

In [ ]:
n,x=map(int,input().split())
student_marks=[]

for i in range(x):
    marks=map(float,input().split())
    student_marks.append(marks)
    
asd=list(zip(*student_marks))

for _ in asd:
    print(round(sum(_)/x,2))

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


##Cara 4

In [ ]:
N, X = map(int, input().split())
lst = []
for _ in range(X):
    lst.append(list(map(float, input().split())))
print(*map(lambda i:sum(i)/X, zip(*lst)), sep='\n')

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


#Input()

##Cara 1

In [ ]:
x, k = map(int, input().split())
exec('result =' + input())
print('True') if result == k else print('False')

1 4
x**3 + x**2 + x + 1
True


##Cara 2

In [ ]:
x, k = map(int, input().split())
exec('result =' + input())
print(result == k)

1 4
x**3 + x**2 + x + 1
True


##Cara 3

In [ ]:
x,k = input().split()

polynomial = input() 
result = eval(polynomial.replace("x",str(x))) 
if result == int(k): 
  print(True) 
else: 
  print(False)

1 4
x**3 + x**2 + x + 1
True


##Cara 4

In [ ]:
x,k = input().split()

p = input()

print(eval(p.replace("x",x)) == int(k))

1 4
x**3 + x**2 + x + 1
True


#Python Evaluation

In [ ]:
#print(eval(input().strip()))
eval(input().strip())

print(2 + 3)
5


#Athlete Sort

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
#answer#-----------------------------------------------
    arr.sort(key=lambda x: x[k])

    for line in arr:
      print(*line)

5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


#Any or All

##Cara 1

In [ ]:
_, nums = input(), input().split()
print(all(n[0] != '-' for n in nums) and any(n == n[::-1] for n in nums))

5
12 9 61 5 14 
True


##Cara 2

In [ ]:
N, lst = int(input()), list(map(int, input().split()))
print(all([i>0 for i in lst]) and any([str(j)==str(j)[::-1] for j in lst]))

5
12 9 61 5 14 
True


##Cara 3

In [ ]:
n, num_list = int(input()), input().split()

print(all(int(number) > 0 for number in num_list) and any(str(number) == str(number)[::-1] for number in num_list))

5
12 9 61 5 14 
True


##Cara 4

In [ ]:
rng, ls = [list(map(int, input().split())) for _ in range(2)] 
print("False"  if  not  all(list(map(lambda x: x>0, ls)))  else \
 "True" if  any(list(map(lambda  no:  no  ==  int(str(no)[::-1]),  ls  ))) else  "False")

5
12 9 61 5 14 
True


#Ginorts

##Cara 1

In [ ]:
s=input()
L0=[]
L1=[]
L2=[]
L3=[]
L4=[]
for i in sorted(s):
    
    if i.isupper():
        L2.append(i)
    elif i.islower():
        L1.append(i)
    elif i.isdigit() and int(i)%2!=0:
        L3.append(i)
    elif i.isdigit() and int(i)%2==0:
        L4.append(i)
        

L0=L1+L2+L3+L4
for _ in L0:
    print(_,end='')

Sorting1234
ginortS1324

##Cara 2

In [ ]:
chars = sorted(input())
chars.sort(key=lambda x: (x.isdigit(), x.isupper(), x.islower(), x in "24680"))
print(*chars, sep="")

Sorting1234
ginortS1324


#Detect Floating Point Number

##Cara 1

In [ ]:
import re
for _ in range(int(input())):
    print(re.fullmatch(r'[+-]?\d*\.\d+', input()) != None)

4
4.000
True
-1.00
True
+4.54
True
SomeRandomStuff
False


##Cara 2

In [ ]:
import re
for _ in range(int(input())):
    print(bool(re.fullmatch('[+-]?\d*\.\d+', input())))

4
4.0O0
False
-1.00
True
+4.54
True
SomeRandomStuff
False


##Cara 3

In [ ]:
import re
for _ in range(int(input())):
    print(re.fullmatch(r'[+-]?\d*\.\d+', input()) is not None)

4
4.000
True
-1.00
True
+4.54
True
SomeRandomStuff
False


##Cara 4

In [ ]:
def main():
    pattern = r"^[+-]?\d*\.\d+$"
    t = int(input())
    for _ in range(t):
        s = input()
        print(True if re.match(pattern, s) else False)
#finding float value is true or false
t=int(input())
k=[]
for i in range(t):
    n=input()
    c=n.count('.')

    if c==1:
        
        ind=n.index('.')
        if n[-1]=='.' or n.isalnum() or n.isalpha() or '.' not in n or '-+' in n or '+-' in n: #return False
            k.append(False)
        elif (n[0]=='+' or n[0]=='-') and n[1:ind].isdigit() and n[ind+1:].isdigit():
            
            k.append(True)
        elif n[0]=='.' and n[1:].isdigit():
            k.append(True)
        elif (n[0]=='+' or n[0]=='-') and n[1]=='.' and n[2:].isdigit():
           k.append(True)
        elif n[0].isdigit() and n[:-1].isdigit():
           k.append(True)
        elif n[0].isdigit() and n[ind+1:].isdigit() and n[:ind].isdigit():
            k.append(True)
        else:
            k.append(False)
    else:
        k.append(False)
for j in k:
    print(j)

4
4.000
-1.00
+4.54
SomeRandomStuff
True
True
True
False


#Re.split()

##Cara 1

In [ ]:
regex_pattern = r"[,.]" # Do not delete 'r'.

import re 
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


##Cara 2

In [ ]:
regex_pattern = r"[\b\W\b]+" # Do not delete 'r'.

import re

print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


##Cara 3

In [ ]:
regex_pattern = r"\W" # Do not delete 'r'.

import re 
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


#Group(),Groups and Groupdict()

##Cara 1

In [ ]:
import re

S = input()
if 0 < len(S) < 100:
    out = re.search(r"([0-9a-zA-Z])\1+", S)
    print(out.group(1)) if out else print(-1)

..12345678910111213141516171820212223
1


##Cara 2

In [ ]:
import re
try: print(re.search(r'([^\W_])\1+',input()).group(1))
except AttributeError: print(-1)

..12345678910111213141516171820212223
1


##Cara 3

In [ ]:
from re import search

regex = search(r"([0-9a-zA-Z])\1+", input())

print(regex.group(1)) if regex is not None else print("-1")

..12345678910111213141516171820212223
1


##Cara 4

In [ ]:
s = str(input())

found = False
for i in range(len(s)-1):
    if s[i].isalnum():
        if s[i] == s[i+1]:
            found = True
            print(s[i])
            break
if not found:
    print(-1)

..12345678910111213141516171820212223
1


##Cara 5

In [ ]:
import re 
m = re.search(r"([a-z0-9])\1{1,}", input()) 
if m: print(m.group(1)) 
else: print(-1)

..12345678910111213141516171820212223
1


#Re.findall() & Re.finditer()

##Cara 1

In [ ]:
import re
v, c = '[aeiou]', '[qwrtypsdfghjklzxcvbnm]'
pt = '(?<=' + c +')' + v + '{2,}(?=' + c + ')'
lst = [i.group() for i in re.finditer(pt, input(), flags=re.I)]
print(*lst, sep='\n') if len(lst)>0 else print(-1)

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


##Cara 2

In [ ]:
import re

result = re.findall(r'(?<=[^aeiou])[aeiou]{2,}(?=[^aeiou])', input(), flags=re.I)
print("\n".join(result) if result else "-1")

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


##Cara 3

In [ ]:
import re

S=input()
#print(S)

m=re.findall(r'(?=([^AEIOUaeiou])([AEIOUaeiou]{2,})([^AEIOUaeiou]))',S)
#print(m)

if m:
    for _ in m:
        print(_[1])
else:
    print(-1)

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


##Cara 4

In [ ]:
from re import findall

pattern = (
    r"[qwrtypsdfghjklzxcvbnmQWRTYPSDFGHJKLZXCVBNM]"
    r"([aeiouAEIOU]{2,})"
    r"(?=[qwrtypsdfghjklzxcvbnmQWRTYPSDFGHJKLZXCVBNM])"
)
regex = findall(pattern, input())

print("\n".join(regex)) if regex else print("-1")

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


#Validating phone numbers


##Cara 1

In [ ]:
import re
for _ in range(int(input())):
    print("YES" if re.fullmatch(r'[789][0-9]{9}', input()) else "NO")

2
9587456281
YES
1252478965
NO


##Cara 2

In [ ]:
N = int(input()) 
pattern = '[789][0-9]{9}$' 
for i in range(N): 
  if (re.match(pattern,input())): 
    print('YES')
  else:
    print('NO')

2
9587456281
YES
1252478965
NO


##Cara 3

In [ ]:
print(*['YES' if bool(__import__('re').search("^[789]{1}\d{9}$", input())) else 'NO' for _ in range(int(input()))], sep='\n')

2
9587456281
1252478965
YES
NO


##Cara 4

In [ ]:
if __name__=='__main__':
    for i in range(int(input())):
        a=input()
        if len(a)==10 and a.isnumeric()==True and int(a[0]) in [7,8,9]:print("YES")
        else:print("NO")

2
9587456281
YES
1252478965
NO


##Cara 5

In [ ]:
import re

regex_pattern = r"^(9|8|7)(\d{9})$"    # Do not delete 'r'.

a = int(input())
b = []
for _ in range(a):
    m = re.match(regex_pattern, input())
    if m: 
        print("YES") 
    else: 
        print("NO")

2
9587456281
YES
1252478965
NO


#Map and Lambda Function

##Cara 1

In [ ]:
cube = lambda x: x **3 # complete the lambda function 

def fibonacci(n):
    # return a list of fibonacci numbers
    x1 = 0 
    x2 = 1
    list1 = []
    
    count = 0
    while count < n:
        list1.append(x1)
        nth = x1+x2
        x1 = x2
        x2 = nth
        count += 1
    return list1
    
if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


##Cara 2

In [ ]:
cube = lambda x: x **3 # complete the lambda function 

def fibonacci(n):
    """Return a Fibonacci sequence with n components"""
    fibonacci_list = []
    for i in range(n):
        if len(fibonacci_list) > 1:
            fibonacci_list.append(fibonacci_list[-1]+fibonacci_list[-2])
        else:
            fibonacci_list.append(i)
    # return a list of fibonacci numbers
    return fibonacci_list
    
if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


##Cara 3

In [ ]:
cube = lambda x: x **3 # complete the lambda function 

def fibonacci(n):
    fib = list()
    x, y = 0, 1
    for i in range(n):
        fib.append(x)
        x, y = y, x + y
    return fib
    
if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


##Cara 4

In [ ]:
cube = lambda x: pow(x, 3) # complete the lambda function 

def fibonacci(n):
    fib = [0, 1]
    if n == 0:
        fib.clear()
    elif n == 1:
        fib = [0, ]
    else:
        for i in range(2, n):
            fib.append(sum(fib[i - 2:i]))
    return fib
    
if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


#Validating Email Addresses With a Filter

##Cara 1

In [ ]:
import re

def fun(s):
    pattern = r'^[a-zA-Z0-9-_]+@[a-zA-Z0-9]+\.[a-zA-Z]{1,3}$'
    return re.match(pattern, s)

def filter_mail(emails):
    return list(filter(fun, emails))

if __name__ == '__main__':
    n = int(input())
    emails = []
    for _ in range(n):
        emails.append(input())
        
filtered_emails = filter_mail(emails)
filtered_emails.sort()
print(filtered_emails)

3
a@gmail.com
b@gmail.com
c@gmail.com
['a@gmail.com', 'b@gmail.com', 'c@gmail.com']


##Cara 2

In [ ]:
import re
def fun(s):
    # return True if s is a valid email, else return False
    p=r'([a-zA-Z0-9\-\_]+)\@{1}([a-zA-Z0-9]+)\.{1}([a-zA-Z]{1,3})'
    if re.fullmatch(p,s):
        return True
    else:
        return False
def filter_mail(emails):
    return list(filter(fun, emails))

if __name__ == '__main__':
    n = int(input())
    emails = []
    for _ in range(n):
        emails.append(input())

filtered_emails = filter_mail(emails)
filtered_emails.sort()
print(filtered_emails)

3
a@gmail.com
b@gmail.com
c@gmail.com
['a@gmail.com', 'b@gmail.com', 'c@gmail.com']


##Cara 3

In [ ]:
import string as s
l,n,a = s.ascii_letters, s.digits, '_-'
lna, ln = l+n+a, l+n

def fun(s):
    x = s.partition('@')
    y = x[2].partition('.')
    cnd1 = all(i in lna for i in x[0]) and (x[1] == '@')
    cnd2 = all(i in ln for i in y[0]) and y[1] == '.'
    cnd3 = all(i in l for i in y[2]) and len(y[2]) <= 3
    cnd4 = len(x[0]) > 0 and len(y[0]) > 0
    
    return all([cnd1,cnd2,cnd3,cnd4])
def filter_mail(emails):
    return list(filter(fun, emails))

if __name__ == '__main__':
    n = int(input())
    emails = []
    for _ in range(n):
        emails.append(input())

filtered_emails = filter_mail(emails)
filtered_emails.sort()
print(filtered_emails)

3
a@gmail.com
b@gmail.com
c@gmail.com
['a@gmail.com', 'b@gmail.com', 'c@gmail.com']


##Cara 4

In [ ]:
import re


def fun(s):
    reg_pattern = r"[@.]"
    split_email = list(re.split(reg_pattern, s))
    if len(split_email) == 3:
        if split_email[2].isalpha() and len(split_email[2]) < 4:
            if split_email[1].isalnum():
                pattern = r"[_-]"
                t = re.split(pattern, split_email[0])
                for item in t:
                    if item.isalnum():
                        return True
        else:
            False
def filter_mail(emails):
    return list(filter(fun, emails))

if __name__ == '__main__':
    n = int(input())
    emails = []
    for _ in range(n):
        emails.append(input())

filtered_emails = filter_mail(emails)
filtered_emails.sort()
print(filtered_emails)

3
a@gmail.com
b@gmail.com
c@gmail.com
['a@gmail.com', 'b@gmail.com', 'c@gmail.com']


#Reduce Function

##Cara 1

In [ ]:
from fractions import Fraction
from functools import reduce

def product(fracs):
    t = reduce(lambda x, y: x * y, fracs)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)


3
1 2
3 4
10 6
5 8


##Cara 2

In [ ]:
from fractions import Fraction
from functools import reduce

def product(fracs):
    t = Fraction(reduce(lambda x,y: x * y, fracs))
    return (t.numerator, t.denominator)

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

3
1 2
3 4
10 6
5 8


##Cara 3

In [ ]:
from fractions import Fraction
from functools import reduce

def product(fracs):
    '''t = Fraction(1/1)
    for i in range(0,len(fracs)):
        t = t*fracs[i]
    '''
    t = reduce(lambda x,y: x*y, fracs, Fraction(1/1))
    
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)


3
1 2
3 4
10 6
5 8


##Cara 4

In [ ]:
from fractions import Fraction
from functools import reduce

def product(fracs):
    t = reduce(lambda acc, f: acc*f, fracs, 1)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

3
1 2
3 4
10 6
5 8


#Words Score

In [ ]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            #++score this is wrong
            score += 1 
    return score


n = int(input())
words = input().split()
print(score_words(words))

3
programming is awesome
4


#Validating and Parsing Email Addresses

##Cara 1

In [ ]:
from re import fullmatch as fm
for _ in range(int(input())):
    if not fm(r'[^\W\d_]+ <[^\W\d_][\w._-]*@[^\W\d_]+\.[^\W\d_]{1,3}>', s:=input()) is None:
        print(s)

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


##Cara 2

In [ ]:
# in this task, we first use a regex pattern to validate if an email is valid.
# after that, we pass the email into email.utils.formataddr to print it out accordingly
import re
from email.utils import parseaddr, formataddr
p = re.compile("^[A-Za-z]{1}[A-Za-z0-9-_\.]+@{1}[A-Za-z]+\.{1}[A-Za-z]{1,3}$")
items_lists = [input().split() for _ in range(int(input()))]
# email_list = [item[1].rstrip(">").lstrip("<") for item in items_lists]
# true_emails = [i for i in email_list if p.search(i) is not None]
for i in items_lists:
    if p.search(i[1].rstrip(">").lstrip("<")) is not None:
        print(formataddr((i[0], i[1].rstrip(">").lstrip("<"))))

2
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>
DEXTER <dexter@hotmail.com>


##Cara 3

In [ ]:
from re import fullmatch
from email.utils import parseaddr

N = int(input())

for _ in range(N):
    input_line = input()

    if fullmatch(r"[a-zA-Z][a-zA-Z0-9_\-\.]+@[a-zA-Z]+\.[a-zA-Z]{1,3}", parseaddr(input_line)[1]):
        print(input_line)

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>
