#Detect HTML Tags, Attributes and Attribute Values

##Cara 1

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        [print(f'-> {i[0]} > {i[1]}') for i in attrs]
    def handle_startendtag(self, tag, attrs):
        print (tag)
        [print(f'-> {i[0]} > {i[1]}') for i in attrs]
        
parser = MyHTMLParser()
for _ in range(int(input())):
    parser.feed(input())

9
<head>
head
<title>HTML</title>
title
</head>
<object type="application/x-flash" 
data="your-file.swf" 
width="0" height="0">
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
<!-- <param name="movie" value="your-file.swf" /> -->
<param name="quality" value="high"/>
param
-> name > quality
-> value > high
</object>


##Cara 2

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        for attr in attrs:
            print(f'-> {attr[0]} > {attr[1]}')
    
    def handle_startendtag(self, tag, attrs):
        print(tag)
        for attr in attrs:
            print(f'-> {attr[0]} > {attr[1]}')

parser = MyHTMLParser()
for _ in range(int(input())):
    parser.feed(input())

9
<head>
head
<title>HTML</title>
title
</head>
<object type="application/x-flash" 
data="your-file.swf" 
width="0" height="0">
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
<!-- <param name="movie" value="your-file.swf" /> -->
<param name="quality" value="high"/>
param
-> name > quality
-> value > high
</object>


##Cara 3

In [ ]:
from html.parser import HTMLParser


class Kevin(HTMLParser):
    def handle_starttag(self, tag, attr):
        print(tag)
        if attr:
            for item in attr:
                print("->", item[0], ">", item[1])


html_code = [input() for _ in range(int(input()))]

my_object = Kevin()
my_object.feed("".join(html_code))

9
<head>
<title>HTML</title>
</head>
<object type="application/x-flash" 
data="your-file.swf" 
width="0" height="0">
<!-- <param name="movie" value="your-file.swf" /> -->
<param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


##Cara 4

In [ ]:
from html.parser import HTMLParser


class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)

        for attr in attrs:
            print(f"-> {attr[0]} > {attr[1]}")

N = int(input())
parser = MyHTMLParser()

parser.feed("\n".join([input() for _ in range(N)]))

9
<head>
<title>HTML</title>
</head>
<object type="application/x-flash" 
data="your-file.swf"
width="0" height="0">
<!-- <param name="movie" value="your-file.swf" /> -->
<param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


##Cara 5

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attr):
        print(tag)
        for i in attr:
            print(f'-> {i[0]} > {i[1]}')
   
html=""
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
                
parser = MyHTMLParser()
parser.feed(html)
parser.close()

9
<head>
<title>HTML</title>
</head>
<object type="application/x-flash" 
data="your-file.swf"
width="0" height="0">
<!-- <param name="movie" value="your-file.swf" /> -->
<param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


#Vallidating UID

##Cara 1

In [ ]:
import re
upper2_re = re.compile(r'[A-Z].*[A-Z]')
digit3_re = re.compile(r'[0-9].*[0-9].*[0-9]')
nonchars_re = re.compile(r'[^0-9a-zA-Z]')
for _ in range(int(input())):
    s = input()
    if 10 == len(s) == len(set(s)) \
            and nonchars_re.search(s) is None \
            and upper2_re.search(s) is not None \
            and digit3_re.search(s) is not None:
        print("Valid")
    else:
        print("Invalid")

2
B1CD102354
Invalid
B1CDEF2354
Valid


In [ ]:
from re import fullmatch as fm

for _ in range(int(input())):
    s = input()
    c = fm(r'(?=.*[A-Z].*[A-Z])(?=.*\d.*\d.*\d)[^\W_]{10}', s)
    r = fm(r'(?:([^\W_])(?!.*\1))*', s)
    print('Valid' if None not in (c, r) else 'Invalid')

2


In [ ]:
from re import fullmatch as fm
for _ in range(int(input())):
    c = fm(r'(?=.*[A-Z].*[A-Z])(?=.*\d.*\d.*\d)[^\W_]{10}', s:=input())
    r = fm(r'(?:([^\W_])(?!.*\1))*', s)
    print('Valid') if None not in (c, r) else print('Invalid')

Invalid
Valid


In [ ]:
import re

for _ in range(int(input())):
    uid = input()
    if re.search("[\d]{3,}[A-Z]{2,}", ''.join(sorted([*uid]))) \
                 and sum([1 for i in set(uid) if uid.count(i)>1])==0 \
                 and re.search("[a-zA-Z0-9]", uid) \
                 and len(uid)==10:
        print("Valid")
    else:
        print("Invalid")

Invalid
Valid


In [ ]:
uids = []
for i in range(int(input())):
    uids.append(input())
    
for uid in uids:
    valid = len([x for x in uid if x.isupper()]) > 1
    valid = valid and len([x for x in uid if x.isdigit()]) > 2
    valid = valid and all([x.isalnum() for x in uid])
    valid = valid and len(set([x for x in uid])) == 10
    valid = valid and len(uid) == 10
    print('Valid' if valid else 'Invalid')

In [ ]:
import re

# Define constants
MUST_PATTERNS = [r'[A-Z].*[A-Z]', r'\d.*\d.*\d', r'^[a-zA-Z0-9]{10}$']
MUST_NOT_PATTERN = r'([a-zA-Z0-9]).*\1'

# Define function to check IDs
def is_valid_password(password):
    # Check all must patterns
    must_patterns_matched = all(re.search(p, password) for p in MUST_PATTERNS)
    
    # Check must not pattern
    must_not_pattern_matched = not re.search(MUST_NOT_PATTERN, password)
    
    return must_patterns_matched and must_not_pattern_matched

# Get inputs
num_inputs = int(input())
inputs = [input() for _ in range(num_inputs)]

# Check ID's and print result
results = [is_valid_password(p) for p in inputs]
print(*["Valid" if x else "Invalid" for x in results], sep="\n")

#Validating Credit Card Numbers

#Validating Postal Codes

#Inner and Outer

#XML2 - Find the Maximum Depth


##Cara 1

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    if level+1 > maxdepth: maxdepth = level+1
    [depth(child, level+1) for child in elem]   
    return  maxdepth

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
1


##Cara 2

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    maxdepth = level + 1 if level + 1 > maxdepth else maxdepth

    for child in elem:
        depth(child, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
1


#XML2 - Find the Maximum Depth

##Cara 1

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    if level+1 > maxdepth: maxdepth = level+1
    [depth(child, level+1) for child in elem]   
    return  maxdepth

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
1


##Cara 2

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    maxdepth = max(maxdepth, level + 1)
    [depth(ch, level + 1) for ch in elem]

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
1


#Min and Max

##Cara 1

In [ ]:
import numpy
N, M = map(int, input().split())
arr = []
for i in range(N):
    f = list(map(int, input().split()))
    arr.append(f)

print(numpy.max(numpy.min(numpy.array(arr), axis=1)))

4 2
2 5
3 7
1 3
4 0
3


##Cara 2

In [ ]:
import numpy as np
N, M = map(int, input().split())
arr = np.array([input().split() for _ in range(N)], int)
print(np.max(np.min(arr, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


##Cara 3

In [ ]:
import numpy as np
print(np.max(np.min(np.array([input().split() for _ in range(int(input().split()[0]))], int), axis=1)))

4 2
2 5
3 7
1 3
4 0
3


##Cara 4

In [ ]:
import numpy as np
n, m = map(int, input().strip().split(' '))
inp_arr = [[int(i) for i in input().strip().split(' ')] for _ in range(n)]
print(np.max(np.min(inp_arr, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


#Standardize Mobile Number Using Decorators


##Cara 1

In [ ]:
def wrapper(f):
    def fun(l):
        # complete the function
        l = ['+91 '+i[-10:-5]+' '+i[-5:] for i in l]
        f(l)
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


##Cara 2

In [ ]:
def wrapper(f):
    def fun(l):
        # this is where we will instance the function f()
        # we also need to edit the numbers in the list l
        ten_digit_numbers = [i[-10:-5]+ " " + i[-5:] for i in l]
        numbers_plus91 = ["+91 " + item for item in ten_digit_numbers]
        f(numbers_plus91)
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


##Cara 3

In [ ]:
def wrapper(f):
    def fun(l):
        p=list()
        for x in l:
            x=x[-10:]
            p.append(x)
        p=sorted(p)
        for _ in p:            
            print('+91',_[-10:-5],_[-5:])
    return fun
    
@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


##Cara 4

In [ ]:
def wrapper(f):
    def fun(l):
        lst = []
        for no in l:
            phone_num = no[::-1][:10][::-1]
            correct_format_num = "+91" + " " + phone_num[:5] + " " + phone_num[5:]
            lst.append(correct_format_num)
        f(lst)
            
    return fun    

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


#Decorators 2 - Name Directory

##Cara 1

In [ ]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        for i in people:
            i[2] = int(i[2])
        sorted_list = sorted(people, key=operator.itemgetter(2))
        return list(map(lambda x: f(x), sorted_list))
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


##Cara 2

In [ ]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        sorted_list = sorted(people, key=lambda x: int(x[2]))
        return list(map(lambda each: f(each), sorted_list)) 
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


##Cara 3

In [ ]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        sorted_list = sorted(people, key=lambda x: int(x[2]))
        return list(map(lambda each: f(each), sorted_list)) 
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


##Cara 4

In [ ]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        return [f(person) for person in sorted(people, key=lambda x: int(x[2]))]
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


#Array Mathematics

##Cara 1

In [ ]:
import numpy as np
N, M = map(int, input().split())
lst = ['+','-','*','//','%','**']
A = np.array([input().split() for _ in range(N)], int)
B = np.array([input().split() for _ in range(N)], int)
for i in lst: exec(f'print(A{i}B)')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


##Cara 2

In [ ]:
import numpy as np
n, m = list(map(int, input().strip().split(' ')))

arr1 = np.array([list(map(int, input().strip().split(' '))) for _ in range(n)])
arr2 = np.array([list(map(int, input().strip().split(' '))) for _ in range(n)])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


##Cara 3

In [ ]:
from numpy import array

N, _ = [int(x) for x in input().split()]

A = array([[int(x) for x in input().split()] for _ in range(N)])
B = array([[int(x) for x in input().split()] for _ in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


##Cara 4

In [ ]:
import numpy

n,m=map(int,input().split())
a=[]
b=[]
for i in range(n):
    a.append(list(map(int,input().split())))
for j in range(n):
    b.append(list(map(int,input().split())))

arr1 = numpy.array(a)
arr2 = numpy.array(b)

print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(arr1//arr2)
print(numpy.mod(a, b))
print(numpy.power(a, b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


##Cara 5

In [ ]:
import numpy as np

N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)], int)
B = np.array([input().split() for _ in range(N)], int)
print(A+B, A-B, A*B, A//B, A%B, A**B, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#Floor, Ceil and Rint

##Cara 1

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')
A = [float(i) for i in input().split()]

print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


##Cara 2

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')
arr, lst = np.array(input().split(), float), ['floor','ceil','rint']
for i in lst: exec(f'print(np.{i}(arr))')

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


##Cara 3

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')

Arr=numpy.array(input().split(),float)

print(numpy.floor(Arr))
print(numpy.ceil(Arr))
print(numpy.rint(Arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


##Cara 4

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')

A = numpy.array(input().split(), float)
print(numpy.floor(A), numpy.ceil(A), numpy.rint(A), sep='\n')

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#Sum and Prod

##Cara 1

In [ ]:
import numpy as np
N, M = map(int, input().split())
arr = np.array([input().split() for _ in range(N)], int)
print(np.product(np.sum(arr, axis=0)))

2 2
1 2
3 4
24


##Cara 2

In [ ]:
import numpy as np
n, m = map(int, input().strip().split(' '))
inp_arr = [[int(i) for i in input().strip().split(' ')] for _ in range(n)]
print(np.prod(np.sum(inp_arr, axis = 0)))

2 2
1 2
3 4
24


##Cara 3

In [ ]:
import numpy as np
n, m = map(int, input().split())
print(np.prod(np.sum(np.array([input().split() for _ in range(n)], int), axis=0)))

2 2
1 2
3 4
24


##Cara 4

In [ ]:
from numpy import array, sum, prod

print(
    prod(
        sum(
            array([[int(x) for x in input().split()] for _ in range([int(x) for x in input().split()][0])]), axis=0
        ),
        axis=0,
    )
)

2 2
1 2
3 4
24


#Transpose and Flatten

##Cara 1

In [ ]:
import numpy

N,M = (int(i) for i in input().split())

arr = numpy.array([[int(i) for i in input().split()] for j in range(N)])

print(numpy.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


##Cara 2

In [ ]:
import numpy as np
N, M = map(int, input().split())
lst = np.array([input().split() for _ in range(N)], int)
print(lst.transpose(), lst.flatten(), sep='\n')

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


##Cara 3

In [ ]:
from numpy import array, transpose

arr = array([[int(x) for x in input().split()] for _ in range([int(x) for x in input().split()][0])])

print(transpose(arr), arr.flatten(), sep="\n")

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#Concatenate


##Cara 1

In [ ]:
import numpy as np
N, M, P = map(int, input().split())
arr1 = np.array([input().split() for _ in range(N)], int)
arr2 = np.array([input().split() for _ in range(M)], int)
print(np.concatenate([arr1, arr2]))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


##Cara 2

In [ ]:
import numpy as np
n, m, p = list(map(int, input().split()))
a = np.array([input().split() for p in range(n)], int)
b = np.array([input().split() for p in range(m)], int)
print(np.concatenate((a, b), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


#Mean, Var, and Std

##Cara 1

In [ ]:
import numpy as np
arr = np.array([input().split() for _ in range(int(input().split()[0]))], int)
print(np.mean(arr,axis=1), np.var(arr,axis=0), round(np.std(arr),11), sep='\n')

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


##Cara 2

In [ ]:
import numpy

n ,m = map(int, input().split())
l = numpy.array([input().split() for i in range(n)], int)

print(numpy.mean(l, axis = 1))
print(numpy.var(l, axis =0 ))
print(round(numpy.std(l),11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


##Cara 3

In [ ]:
import numpy as np
n, m = map(int, input().strip().split(' '))
inp_arr = np.array([[int(i) for i in input().strip().split(' ')] for _ in range(n)])
print(np.mean(inp_arr, axis = 1))
print(np.var(inp_arr, axis = 0))
print(np.std(inp_arr))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


##Cara 4

In [ ]:
import numpy
nm = input()
inm = nm.split( )
inn = []
for i in inm:
    i = int(i)
    inn.append(i)

arr = []

for i in range(0, inn[0]):
    a = input()
    k = []
    b = a.split(" ")

    for i in b:
        i = int(i)
        k.append(i)
    arr.append(k)

arn = numpy.array(arr)
print(numpy.mean(arn, axis=1))
print(numpy.var(arn, axis=0))
z = numpy.std(arn, axis=None)
j = round(z, 11)
print(j)

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


#Dot and Cross

##Cara 1

In [ ]:
import numpy as np
N = int(input())
A = np.array([input().split() for _ in range(N)], int)
B = np.array([input().split() for _ in range(N)], int)
print(np.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


##Cara 2

In [ ]:
import numpy as np
n = int(input().strip())
arr1 = np.array([[int(i) for i in input().strip().split(' ')] for _ in range(n)])
arr2 = np.array([[int(i) for i in input().strip().split(' ')] for _ in range(n)])
print(np.dot(arr1, arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


##Cara 3

In [ ]:
import numpy

N = int(input())

A = numpy.array([input().split() for _ in range(N)], int)
B = numpy.array([input().split() for _ in range(N)], int)

print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


##Cara 4

In [ ]:
from numpy import array, dot

N = int(input())
A, B = [array([[int(x) for x in input().split()] for _ in range(N)]) for _ in range(2)]

print(dot(A, B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


#Polynomials

##Cara 1

In [ ]:
import numpy as np
print(np.polyval(list(map(float, input().split())), float(input())))

1.1 2 3
0
3.0


##Cara 2

In [ ]:
import numpy

coef_p=list(map(float,input().split()))
x=int(input())
print(numpy.polyval(coef_p,x))

1.1 2 3
0
3.0
